### ISSUE TITLE
moveit-builder branch commits

### ISSUE THREAD

**Issue by JafarAbdi** [JafarAbdi/moveit2#21]
- Remove the shared_ptr holder for `MotionPlanResponse`: It's being used at all
- Making trajectory return a copy: Otherwise it segfault while destructing with the following stacktrace
```cpp
      .def_property_readonly(
          "trajectory",
          [](const planning_interface::MotionPlanResponse& self) {
            // Fix memory issue:
            // - https://github.com/NGSolve/ngsolve/commit/8d982e5a9a282fc20a27d62a45c900e8fbb5fe29#diff-52f79a720c00cb5b96fb842fc1f8f5c88929e28782cd4986d42b9c556293009cR9
            // - https://github.com/pybind/pybind11/issues/1389
            // - https://github.com/pybind/pybind11/issues/1333
            // - https://github.com/pybind/pybind11/issues/4603
            // - https://github.com/pybind/pybind11/issues/1145
            return robot_trajectory::RobotTrajectory(*self.trajectory, true);
          },
          py::return_value_policy::reference_internal)
```

- If MotionPlanResponse has shared_ptr holder

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff3c30b17 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555556a4b900) at /usr/include/c++/11/bits/shared_ptr_base.h:168
168                 _M_dispose();
(gdb) bt
#0  0x00007ffff3c30b17 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555556a4b900)
    at /usr/include/c++/11/bits/shared_ptr_base.h:168
#1  0x00007ffff3c33180 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:705
#2  std::__shared_ptr<robot_trajectory::RobotTrajectory, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>,
    this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#3  std::shared_ptr<robot_trajectory::RobotTrajectory>::~shared_ptr (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr.h:122
#4  planning_interface::MotionPlanResponse::~MotionPlanResponse (this=<optimized out>, this=<optimized out>)
    at /opt/ros/humble/include/moveit_core/moveit/planning_interface/planning_response.h:48
#5  std::_Sp_counted_ptr<planning_interface::MotionPlanResponse*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (
    this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:348
#6  0x00007ffff3c30b1a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555556a7dc10)
    at /usr/include/c++/11/bits/shared_ptr_base.h:168
#7  0x00007ffff3c30eea in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>,
    this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:705
#8  std::__shared_ptr<planning_interface::MotionPlanResponse, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (
    this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#9  std::shared_ptr<planning_interface::MotionPlanResponse>::~shared_ptr (this=<optimized out>, this=<optimized out>)
    at /usr/include/c++/11/bits/shared_ptr.h:122
#10 pybind11::class_<planning_interface::MotionPlanResponse, std::shared_ptr<planning_interface::MotionPlanResponse> >::dealloc (v_h=...) at /usr/include/pybind11/pybind11.h:1670
#11 0x00007ffff4cfe2a8 in ?? ()
   from /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/_rclpy_pybind11.cpython-310-x86_64-linux-gnu.so
#12 0x00005555556a6ec0 in _Py_Dealloc (op=<optimized out>) at ../Objects/object.c:2301
#13 _Py_DECREF (op=<optimized out>) at ../Include/object.h:500
#14 frame_dealloc (
```

- Without holder

**Comment by JafarAbdi** [comment]
```
            // Fix memory issue:
            // -
            // https://github.com/NGSolve/ngsolve/commit/8d982e5a9a282fc20a27d62a45c900e8fbb5fe29#diff-52f79a720c00cb5b96fb842fc1f8f5c88929e28782cd4986d42b9c556293009cR9
            // - https://github.com/pybind/pybind11/issues/1389
            // - https://github.com/pybind/pybind11/issues/1333
            // - https://github.com/pybind/pybind11/issues/4603
            // - https://github.com/pybind/pybind11/issues/1145
```
